using ClinicApi.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace ClinicApi.Api.Data;

public class ClinicDbContext : DbContext
{
    public ClinicDbContext(DbContextOptions<ClinicDbContext> options)
        : base(options)
    {
    }

    public DbSet<Department> Departments => Set<Department>();
    public DbSet<User> Users => Set<User>();
    public DbSet<Doctor> Doctors => Set<Doctor>();
    public DbSet<Patient> Patients => Set<Patient>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // ⚠️ 刻意保留的差異：所有主鍵都沒設 UseIdentityAlwaysColumn()。
        //    EF 的預設會產出 GENERATED BY DEFAULT AS IDENTITY，
        //    但 schema.sql 寫的是 GENERATED ALWAYS AS IDENTITY。
        //    留著是為了在比對 migration 時親眼看到這個差異（patients 表裡
        //    id 和 mrn 會一個 BY DEFAULT、一個 ALWAYS，剛好並排對照）。

        // ============================================================
        // departments  ※ 教練示範
        // ============================================================
        modelBuilder.Entity<Department>(e =>
        {
            e.HasKey(x => x.Id);

            e.Property(x => x.Name).HasMaxLength(50);
            e.Property(x => x.Phone).HasMaxLength(30);
            // Address 不設 HasMaxLength -> text

            e.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
            e.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");

            e.HasIndex(x => x.Name)
             .IsUnique()
             .HasFilter("deleted_at IS NULL")
             .HasDatabaseName("ux_departments_name_active");
        });

        // ============================================================
        // users  ※ 教練示範
        // ============================================================
        modelBuilder.Entity<User>(e =>
        {
            e.HasKey(x => x.Id);

            e.Property(x => x.Name).HasMaxLength(50);
            e.Property(x => x.Account).HasMaxLength(255);
            e.Property(x => x.PasswordHash).HasMaxLength(255);
            e.Property(x => x.Role).HasMaxLength(50);

            e.Property(x => x.IsActive).HasDefaultValue(true);
            e.Property(x => x.TryCount).HasDefaultValue((short)0);

            e.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
            e.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");

            e.HasIndex(x => x.Account).IsUnique();

            e.ToTable(t => t.HasCheckConstraint(
                "ck_users_role",
                "role IN ('admin', 'doctor', 'patient', 'staff')"));
        });

        // ============================================================
        // doctors  ← Jimison 寫，教練補全
        // ============================================================
        modelBuilder.Entity<Doctor>(e =>
        {
            e.HasKey(x => x.Id);

            e.Property(x => x.License).HasMaxLength(30);
            e.Property(x => x.Phone).HasMaxLength(30);
            // Address / Description 不設 HasMaxLength -> text

            e.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
            e.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");

            // ★ 你漏掉的：關聯設定。
            //   沒有這段，EF 還是會靠 convention 認出 FK，
            //   但刪除行為會變成 EF 的預設值，不是 schema.sql 寫的 RESTRICT。
            //   多對一：一個科別有多位醫師 -> WithMany
            e.HasOne(x => x.Department)
             .WithMany(d => d.Doctors)
             .HasForeignKey(x => x.DepartmentId)
             .OnDelete(DeleteBehavior.Restrict);

            // ★ 你漏掉的：一對一。一個 user 最多對應一位 doctor -> WithOne
            //   WithOne + HasForeignKey<Doctor> 會「自動」在 user_id 上建 UNIQUE 索引，
            //   所以這裡不需要（也不該）再手寫 HasIndex(x => x.UserId).IsUnique()。
            e.HasOne(x => x.User)
             .WithOne(u => u.Doctor)
             .HasForeignKey<Doctor>(x => x.UserId)
             .OnDelete(DeleteBehavior.Restrict);

            // ↓ 這兩條你寫對了
            e.HasIndex(x => x.DepartmentId)
             .HasDatabaseName("idx_doctors_department_id");

            e.HasIndex(x => x.License)
             .IsUnique()
             .HasFilter("deleted_at IS NULL")
             .HasDatabaseName("ux_doctors_license_active");
        });

        // ============================================================
        // patients  ← Jimison 寫，教練補全
        // ============================================================
        modelBuilder.Entity<Patient>(e =>
        {
            e.HasKey(x => x.Id);

            e.Property(x => x.IcId).HasMaxLength(50);
            e.Property(x => x.Phone).HasMaxLength(30);
            // BirthDate 是 DateOnly -> Npgsql 自動對到 date，不用設

            e.Property(x => x.CreatedAt).HasDefaultValueSql("now()");
            e.Property(x => x.UpdatedAt).HasDefaultValueSql("now()");

            // ★ 你漏掉的：mrn 是「第二個 identity 欄位」。
            //   ValueGeneratedOnAdd()      -> 告訴 EF「這欄的值由資料庫產生，別叫我填」
            //                                 （非主鍵欄位一定要明講，主鍵才有 convention）
            //   UseIdentityAlwaysColumn()  -> GENERATED ALWAYS（連 INSERT 都不准硬塞值）
            //   HasIdentityOptions(1000000)-> START WITH 1000000
            e.Property(x => x.Mrn)
             .ValueGeneratedOnAdd()
             .UseIdentityAlwaysColumn()
             .HasIdentityOptions(startValue: 1000000);

            // ★ 你漏掉的：mrn 的 UNIQUE
            e.HasIndex(x => x.Mrn).IsUnique();

            // ★ 你漏掉的：一對一 + RESTRICT（同 doctors，UNIQUE 由 WithOne 自動帶）
            e.HasOne(x => x.User)
             .WithOne(u => u.Patient)
             .HasForeignKey<Patient>(x => x.UserId)
             .OnDelete(DeleteBehavior.Restrict);

            // ↓ 這條你寫對了
            e.HasIndex(x => x.IcId)
             .IsUnique()
             .HasFilter("deleted_at IS NULL")
             .HasDatabaseName("ux_patients_ic_id_active");
        });

        // ============================================================
        // refresh_tokens  ← Jimison 寫，教練補全
        // ============================================================
        modelBuilder.Entity<RefreshToken>(e =>
        {
            e.HasKey(x => x.Id);

            // ★ 你漏掉的：token_hash 的長度限制
            e.Property(x => x.TokenHash).HasMaxLength(64);
            e.Property(x => x.RevokedReason).HasMaxLength(50);

            e.Property(x => x.CreatedAt).HasDefaultValueSql("now()");

            // ★ 你漏掉的：token_hash 的 UNIQUE
            //   這個 UNIQUE 是對的：同一個 hash 值全表只能出現一次。
            e.HasIndex(x => x.TokenHash).IsUnique();

            // ★ 你漏掉的：一對多 + CASCADE
            //   一個 user 可以同時有多張 refresh token（手機一張、筆電一張）
            //   -> WithMany。user 被刪除時 token 一起刪 -> Cascade。
            e.HasOne(x => x.User)
             .WithMany(u => u.RefreshTokens)
             .HasForeignKey(x => x.UserId)
             .OnDelete(DeleteBehavior.Cascade);

            // ★ 你漏掉的：自我參照。
            //   兩個導覽屬性型別都是 RefreshToken，EF 猜不出誰配誰，
            //   而且 FK 屬性叫 ReplacedBy（不是 convention 期待的 ReplacedByTokenId），
            //   所以三件事都要明講：哪一端、對應哪個集合、用哪個欄位當 FK。
            e.HasOne(x => x.ReplacedByToken)
             .WithMany(t => t.Replaces)
             .HasForeignKey(x => x.ReplacedBy)
             .OnDelete(DeleteBehavior.SetNull);

            // ⚠️⚠️ 你這條寫了 .IsUnique()，schema.sql 沒有 —— 已移除，見下方說明。
            //      schema.sql:
            //        CREATE INDEX idx_refresh_tokens_user_active
            //            ON refresh_tokens (user_id) WHERE revoked_at IS NULL;
            //      是 CREATE INDEX，不是 CREATE UNIQUE INDEX。
            e.HasIndex(x => x.UserId)
             .HasFilter("revoked_at IS NULL")
             .HasDatabaseName("idx_refresh_tokens_user_active");
        });
    }
}
