-- =============================================================================
-- EF Core 8 產生的初始 migration SQL
--   產生指令：dotnet ef migrations script -o ../../db/ef-initial.sql
--   ⚠️ 這是「快照」檔。重跑上面那個指令會蓋掉，包含下面所有註解。
--
-- 註解 ★ 是比對 db/schema.sql 之後的答案，供事後複習。
-- 完整說明見：docs/progress/Day3-筆記-EF產出vs手寫SQL.md
-- =============================================================================


-- ★【④ 那張你沒寫過的表】= EF 的「進度表」
--   它記錄「這個資料庫已經套用過哪些 migration」。
--   dotnet ef database update 的流程是：
--     1. 讀這張表 → 知道跑到哪了
--     2. 比對 Migrations/ 資料夾裡的檔案 → 算出還沒跑的有哪些
--     3. 只跑那些
--   ★ 這就是你等一下要踩的坑：你的 clinic 資料庫已經有 5 張表了（psql -f 灌的），
--     但這張表不存在（= EF 認為「這個資料庫一片空白」），
--     所以它會從第一個 migration 開始跑 → CREATE TABLE departments → 撞牆。
--
-- ★ 注意兩個細節：
--   1. 表名是 "__EFMigrationsHistory"（加雙引號的大駝峰），
--      但欄位是 migration_id / product_version（snake_case）。
--      因為表名是 EF 寫死的，欄位名才走我們的 UseSnakeCaseNamingConvention()。
--   2. 這段在 START TRANSACTION 之前 → 它不參與底下的交易，
--      而且用 IF NOT EXISTS，重複執行安全。
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

-- ★【EF 多做的 #4】整份 DDL 包在一個交易裡。
--   PostgreSQL 的 DDL 是可交易的（MySQL 不行），所以如果中間任何一句失敗，
--   全部 rollback，不會留下「建到一半」的資料庫。
--   你手寫的 schema.sql 沒有這個 —— psql -f 灌到一半失敗，前面建好的表會留著。
START TRANSACTION;


-- =============================================================================
-- departments
-- =============================================================================
CREATE TABLE departments (
    -- ★【③ 唯一一個「功能真的不一樣」的地方】
    --   schema.sql 寫的是   GENERATED ALWAYS AS IDENTITY
    --   EF   產出的是       GENERATED BY DEFAULT AS IDENTITY
    --
    --   差在哪（實際行為）：
    --     BY DEFAULT → INSERT INTO departments (id, name) VALUES (99, '眼科');  ✅ 成功
    --     ALWAYS     → 同一句 ❌ ERROR: cannot insert into column "id"
    --                        HINT: Use OVERRIDING SYSTEM VALUE to override.
    --
    --   ALWAYS 比較嚴格：連程式都不准硬塞主鍵，一律由資料庫發號。
    --   BY DEFAULT 允許你在需要時明寫 id（例如 EF 的 HasData 種子資料、
    --   或是從舊系統搬資料要保留原本的 id）。
    --
    --   ★ 我們的決定：接受 EF 的 BY DEFAULT，把 schema.sql 改成一致。
    --     理由不是「約束擋路就拿掉」，而是：之後要用 HasData 塞科別種子資料
    --     （內科/外科/兒科…）時需要明寫 id，ALWAYS 會擋住。
    --     真的要 ALWAYS 的話：在 DbContext 每個 PK 加 .UseIdentityAlwaysColumn()
    id integer GENERATED BY DEFAULT AS IDENTITY,

    -- ★ NOT NULL 是從 C# 的 `string Name`（不可為 null）自動推導出來的，
    --   我們沒寫任何 .IsRequired()。對照 `string? Phone` → 下面那行沒有 NOT NULL。
    name character varying(50) NOT NULL,
    phone character varying(30),
    -- ★ 沒設 HasMaxLength → text（不是 varchar）
    address text,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    -- ★ EF 幫約束取了明確的名字 pk_departments。
    --   schema.sql 是欄位後面直接寫 PRIMARY KEY → PG 自動命名 departments_pkey。
    --   功能相同，只是命名策略不同。
    CONSTRAINT pk_departments PRIMARY KEY (id)
);


-- =============================================================================
-- users
-- =============================================================================
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    -- ★ schema.sql 是 `account varchar(255) NOT NULL UNIQUE`，
    --   EF 把 UNIQUE 拆成獨立的 CREATE UNIQUE INDEX（見檔案下半部 ix_users_account）。
    --   PostgreSQL 底層本來就是同一件事：欄位級 UNIQUE = 一個唯一索引。
    account character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(50) NOT NULL,
    -- ★ HasDefaultValue(true) → DEFAULT TRUE（C# 常數寫死進 DDL）
    is_active boolean NOT NULL DEFAULT TRUE,
    try_count smallint NOT NULL DEFAULT 0,
    last_login_at timestamp with time zone,
    -- ★ HasDefaultValueSql("now()") → DEFAULT (now())（PG 在 INSERT 當下才算）
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT pk_users PRIMARY KEY (id),

    -- ★【② CHECK 約束】→ 保留了 ✅
    --   但這不是 EF 自動的。EF 從 `string Role` 看不出「只能是四個值之一」，
    --   是我們在 OnModelCreating 明寫了：
    --       e.ToTable(t => t.HasCheckConstraint("ck_users_role", "role IN (...)"))
    --   結論：EF 的 convention 永遠不會自己產生 CHECK，明寫才會有。
    CONSTRAINT ck_users_role CHECK (role IN ('admin', 'doctor', 'patient', 'staff'))
);


-- =============================================================================
-- doctors
-- =============================================================================
CREATE TABLE doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    department_id integer,
    user_id bigint,
    license character varying(30) NOT NULL,
    phone character varying(30),
    address text,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    deleted_at timestamp with time zone,
    CONSTRAINT pk_doctors PRIMARY KEY (id),

    -- ★【⑤ 刪除行為】RESTRICT 保留了 ✅
    --   來自 .OnDelete(DeleteBehavior.Restrict)
    --   實際效果：有醫師掛在「內科」底下時，DELETE FROM departments WHERE id=3
    --   會被 PG 擋下 → ERROR: update or delete on table "departments" violates
    --   foreign key constraint on table "doctors"
    --
    -- ★ FK 命名慣例：fk_<自己這張表>_<對方那張表>_<FK欄位>
    --   schema.sql 沒命名 → PG 自動叫 doctors_department_id_fkey
    CONSTRAINT fk_doctors_departments_department_id
        FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_doctors_users_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);


-- =============================================================================
-- patients
-- =============================================================================
CREATE TABLE patients (
    -- ★★ 這兩行並排看，就是「BY DEFAULT vs ALWAYS」最好的教材 ★★
    id bigint GENERATED BY DEFAULT AS IDENTITY,

    -- ★【③ START WITH 1000000】→ 保留了 ✅ 而且是 ALWAYS
    --   來自三個方法串起來：
    --       .ValueGeneratedOnAdd()          「這欄由資料庫產生，別叫我填」
    --                                        （非主鍵欄位一定要明講）
    --       .UseIdentityAlwaysColumn()      → GENERATED ALWAYS
    --       .HasIdentityOptions(startValue: 1000000) → (START WITH 1000000)
    --
    -- ★ 為什麼這裡沒有 NOT NULL？
    --   PostgreSQL 規定：identity 欄位「隱含」NOT NULL，不用也不能再寫一次。
    --   所以跟 schema.sql 的 `NOT NULL` 是等價的，不算差異。
    mrn bigint GENERATED ALWAYS AS IDENTITY (START WITH 1000000),

    user_id bigint,
    ic_id character varying(50) NOT NULL,
    phone character varying(30),
    address text,
    -- ★ C# 的 DateOnly → date（沒有時間、沒有時區）
    birth_date date,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    deleted_at timestamp with time zone,
    CONSTRAINT pk_patients PRIMARY KEY (id),
    CONSTRAINT fk_patients_users_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT
);


-- =============================================================================
-- refresh_tokens
-- =============================================================================
CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    -- ★ NOT NULL：來自 C# 的 `public long UserId`（不可為 null 的 long）
    --   對照 doctors.user_id 是 `long?` → 上面那張表就沒有 NOT NULL
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revoked_reason character varying(50),
    replaced_by bigint,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),

    -- ★【④ 自我參照 FK】→ 保留了 ✅ 含 ON DELETE SET NULL
    --   REFERENCES refresh_tokens (id) —— 指向自己這張表。
    --   來自：
    --       e.HasOne(x => x.ReplacedByToken)
    --        .WithMany(t => t.Replaces)
    --        .HasForeignKey(x => x.ReplacedBy)
    --        .OnDelete(DeleteBehavior.SetNull);
    --   三件事都得明講，因為兩端型別都是 RefreshToken，EF 猜不出誰配誰。
    --
    --   SET NULL 的實際效果：舊 token（id=1）被刪掉時，
    --   指向它的那一列 replaced_by 會自動變成 NULL，而不是連帶被刪、也不是擋住刪除。
    CONSTRAINT fk_refresh_tokens_refresh_tokens_replaced_by
        FOREIGN KEY (replaced_by) REFERENCES refresh_tokens (id) ON DELETE SET NULL,

    -- ★【⑤ CASCADE】保留了 ✅
    --   實際效果：DELETE FROM users WHERE id=42
    --   → 這個人所有的 refresh token 自動一起刪掉（不用你手動清）
    CONSTRAINT fk_refresh_tokens_users_user_id
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);


-- =============================================================================
-- 索引區
-- =============================================================================
-- ★【② 索引數量】
--   schema.sql   = 15 個（5 PK + 5 欄位級 UNIQUE + 5 條顯式 CREATE INDEX）
--   ef-initial   = 16 個（5 PK + 11 條顯式 CREATE INDEX）
--   多 1 個 → 就是最下面的 ix_refresh_tokens_replaced_by（見那一行的說明）


-- ★【① 部分唯一索引的 WHERE】→ 保留了 ✅
--   來自 .HasFilter("deleted_at IS NULL")。
--   ⚠️ HasFilter 收的是「原始 SQL 字串」，EF 完全不解析，
--     所以裡面必須寫資料庫欄位名 deleted_at，寫成 C# 的 DeletedAt 不會編譯錯，
--     要等打到 PostgreSQL 才爆。
--   ⚠️ 它是 PostgreSQL 專屬的（MySQL 沒有部分索引），換 provider 會爛。
CREATE UNIQUE INDEX ux_departments_name_active
    ON departments (name) WHERE deleted_at IS NULL;

-- ★ 我們明寫的普通索引（HasIndex + HasDatabaseName，沒有 IsUnique）
CREATE INDEX idx_doctors_department_id ON doctors (department_id);

-- ★★ 這條「我們沒有手寫」，是 .WithOne() 自動產生的 ★★
--   e.HasOne(x => x.User).WithOne(u => u.Doctor).HasForeignKey<Doctor>(x => x.UserId)
--   → EF 知道這是一對一 → 自動在 user_id 建 UNIQUE 索引。
--   ★ 重點口訣：在 EF 裡你不該手寫 HasIndex(x => x.UserId).IsUnique()。
--     你只要正確描述「這是一對一」(WithOne)，UNIQUE 是「結果」不是「設定」。
CREATE UNIQUE INDEX ix_doctors_user_id ON doctors (user_id);

CREATE UNIQUE INDEX ux_doctors_license_active
    ON doctors (license) WHERE deleted_at IS NULL;

-- ★ 我們明寫的 e.HasIndex(x => x.Mrn).IsUnique()
--   名字是 EF 自己取的（ix_ + 表 + 欄位），因為我們沒加 HasDatabaseName。
--   schema.sql 是欄位級 UNIQUE → PG 會叫它 patients_mrn_key。名字不同，功能相同。
CREATE UNIQUE INDEX ix_patients_mrn ON patients (mrn);

-- ★ 同 ix_doctors_user_id：WithOne() 自動產生的一對一 UNIQUE
CREATE UNIQUE INDEX ix_patients_user_id ON patients (user_id);

CREATE UNIQUE INDEX ux_patients_ic_id_active
    ON patients (ic_id) WHERE deleted_at IS NULL;

-- ★【① 部分索引 + 不是 UNIQUE】
--   ⚠️ Jimison 原本在這條寫了 .IsUnique()，已移除。
--   如果加了 UNIQUE：同一個 user 同時只能有一張未撤銷的 token
--   → Jimison 早上用 iPhone 登入，中午在 MacBook 登入時 INSERT 撞到唯一約束
--   → PG 回 23505 duplicate key → EF 丟 DbUpdateException → 沒人 catch → HTTP 500
--   → 使用者看到「發生錯誤，請稍後再試」（不是友善的「你已在其他裝置登入」）
--   ★ 口訣：FK 加 UNIQUE = 宣告「這是一對一」。
--     加之前先反過來數：「一個對方能有幾個我？」不只一個就不能加。
CREATE INDEX idx_refresh_tokens_user_active
    ON refresh_tokens (user_id) WHERE revoked_at IS NULL;

-- ★★★【② 多出來的那一條，就是這個】★★★
--   我們完全沒寫過它。EF 的規則是：
--     「每一個外鍵欄位都自動建索引，除非你已經自己宣告了同一組欄位的索引。」
--
--   為什麼 EF 要加？因為 FK 欄位幾乎一定會被拿來查詢和 JOIN，
--   而且刪除父列時 PG 必須檢查「有沒有子列指著我」——沒索引就得全表掃描。
--
--   為什麼別的 FK 沒有多長出來？
--     doctors.department_id      → 我們宣告了 idx_doctors_department_id ✅
--     doctors.user_id            → WithOne 產生了 ix_doctors_user_id ✅
--     patients.user_id           → 同上 ✅
--     refresh_tokens.user_id     → 我們宣告了 idx_refresh_tokens_user_active ✅
--     refresh_tokens.replaced_by → 沒人管它 → EF 自己補 ← 就是這條
CREATE INDEX ix_refresh_tokens_replaced_by ON refresh_tokens (replaced_by);

-- ★ 來自 e.HasIndex(x => x.TokenHash).IsUnique()
--   這個 UNIQUE 是對的：同一個 hash 值全表只能出現一次（跟 FK 一對一無關）。
CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON refresh_tokens (token_hash);

-- ★ 來自 e.HasIndex(x => x.Account).IsUnique()
CREATE UNIQUE INDEX ix_users_account ON users (account);


-- ★ 跑完之後，EF 在進度表蓋章：「20260831053905_InitialCreate 這個 migration 我跑過了」
--   下次 database update 讀到這一列，就會跳過它。
INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260831053905_InitialCreate', '8.0.10');

COMMIT;
